# Generated by Django 4.0.7 on 2023-01-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_employee_task_delete_employeetask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
        migrations.AddField(
            model_name='employee',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
