# Generated by Django 4.0.7 on 2023-01-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_delete_register_employee_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='employee_name',
        ),
    ]
