# Generated by Django 4.0.7 on 2023-01-23 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_rename_name_employee_employee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_name',
            new_name='name',
        ),
    ]
