# Generated by Django 4.0.7 on 2023-01-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rename_employee_name_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
