# Generated by Django 4.0.7 on 2023-01-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_task_status_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status_description',
            field=models.TextField(),
        ),
    ]
